version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbAuth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
